simple_select_clause ::=
	'SELECT'  ( ( target_elem ) ( ( ',' target_elem ) )* ) 
( 'FROM' ( ( table_ref ) ( (  ('JOIN'|'OUTER JOIN'|'LEFT OUTER JOIN') table_ref ('ON'|'USING') '(' join_criteria ')' ) )* ) )
 ( ( 'WHERE' a_expr ) |  ) ( 'GROUP' 'BY' group_by_list |  ) ( 'HAVING' a_expr |  ) ( 'ORDER BY' order_list |  )
	